import { DefaultTheme } from 'react-native-paper';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#0ea5e9',
    primaryContainer: '#e0f2fe',
    secondary: '#0284c7',
    secondaryContainer: '#bae6fd',
    tertiary: '#0891b2',
    tertiaryContainer: '#a7f3d0',
    surface: '#ffffff',
    surfaceVariant: '#f1f5f9',
    background: '#f8fafc',
    error: '#ef4444',
    errorContainer: '#fecaca',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#0c4a6e',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#0c4a6e',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#064e3b',
    onSurface: '#1e293b',
    onSurfaceVariant: '#64748b',
    onBackground: '#1e293b',
    onError: '#ffffff',
    onErrorContainer: '#7f1d1d',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    inverseSurface: '#334155',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#7dd3fc',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    ...DefaultTheme.fonts,
    displayLarge: {
      fontFamily: 'System',
      fontSize: 57,
      fontWeight: '400',
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'System',
      fontSize: 45,
      fontWeight: '400',
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'System',
      fontSize: 36,
      fontWeight: '400',
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'System',
      fontSize: 32,
      fontWeight: '600',
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'System',
      fontSize: 28,
      fontWeight: '600',
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'System',
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: 'System',
      fontSize: 22,
      fontWeight: '500',
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    labelLarge: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'System',
      fontSize: 11,
      fontWeight: '500',
      lineHeight: 16,
    },
    bodyLarge: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
    },
  },
  roundness: 8,
  animation: {
    scale: 1.0,
  },
};

export const darkTheme = {
  ...theme,
  dark: true,
  colors: {
    ...theme.colors,
    primary: '#38bdf8',
    primaryContainer: '#0c4a6e',
    secondary: '#0ea5e9',
    secondaryContainer: '#075985',
    tertiary: '#22d3ee',
    tertiaryContainer: '#164e63',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    background: '#0f172a',
    error: '#f87171',
    errorContainer: '#7f1d1d',
    onPrimary: '#0c4a6e',
    onPrimaryContainer: '#e0f2fe',
    onSecondary: '#075985',
    onSecondaryContainer: '#bae6fd',
    onTertiary: '#164e63',
    onTertiaryContainer: '#a7f3d0',
    onSurface: '#f1f5f9',
    onSurfaceVariant: '#cbd5e1',
    onBackground: '#f1f5f9',
    onError: '#7f1d1d',
    onErrorContainer: '#fecaca',
    outline: '#64748b',
    outlineVariant: '#475569',
    inverseSurface: '#f1f5f9',
    inverseOnSurface: '#334155',
    inversePrimary: '#0ea5e9',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.7)',
  },
};

// Common styles used across the app
export const commonStyles = {
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shadow: {
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.roundness,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 16,
    ...this.shadow,
  },
  button: {
    borderRadius: theme.roundness,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  input: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.roundness,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  text: {
    color: theme.colors.onSurface,
    fontSize: 16,
    lineHeight: 24,
  },
  heading: {
    color: theme.colors.onSurface,
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 32,
  },
  subheading: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 28,
  },
  caption: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 12,
    lineHeight: 16,
  },
  error: {
    color: theme.colors.error,
    fontSize: 14,
    lineHeight: 20,
  },
  success: {
    color: theme.colors.tertiary,
    fontSize: 14,
    lineHeight: 20,
  },
};

export default theme;
